mail_location = maildir:/var/mail/%u
mail_privileged_group = mail

protocols = imap

passdb {
  driver = passwd-file
  args = scheme=PLAIN /etc/dovecot/users
}
userdb {
  driver = passwd-file
  args = /etc/dovecot/users
}

service imap-login {
  inet_listener imap {
    port = 143
  }
  inet_listener imaps {
    port = 993
  }
}

ssl = no
