mail_location = maildir:/var/mail/%u
mail_privileged_group = mail
protocols = imap

passdb {
  driver = sql
  args = /etc/dovecot/dovecot-sql.conf.ext
}
userdb {
  driver = sql
  args = /etc/dovecot/dovecot-sql.conf.ext
}

service imap-login {
  inet_listener imap {
    port = 143
  }
}
ssl = no

disable_plaintext_auth = no

log_path = /dev/stderr
info_log_path = /dev/stderr
debug_log_path = /dev/stderr
mail_debug = yes
auth_debug = yes
